# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/Program/0_pyqt5/test/Update.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdateWindow(object):
    def setupUi(self, UpdateWindow):
        UpdateWindow.setObjectName("UpdateWindow")
        UpdateWindow.resize(800, 499)
        self.centralwidget = QtWidgets.QWidget(UpdateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 90, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 20, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 90, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        UpdateWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UpdateWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        UpdateWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UpdateWindow)
        self.statusbar.setObjectName("statusbar")
        UpdateWindow.setStatusBar(self.statusbar)

        self.retranslateUi(UpdateWindow)
        QtCore.QMetaObject.connectSlotsByName(UpdateWindow)

    def retranslateUi(self, UpdateWindow):
        _translate = QtCore.QCoreApplication.translate
        UpdateWindow.setWindowTitle(_translate("UpdateWindow", "MainWindow"))
        self.pushButton.setText(_translate("UpdateWindow", "PushButton"))
        self.pushButton_2.setText(_translate("UpdateWindow", "PushButton"))
